name: publish-to-medium
on:
    workflow_dispatch:
        inputs:
            file:
                type: string
                description: path/to/story.md
                required: true
            tags:
                type: string
                description: Medium post tags
                required: true
            title:
                type: string
                description: Medium post title
                required: true

jobs:
    post-to-medium:
      name: Post to Medium
      runs-on: ubuntu-latest
      steps:
        - name: Check out reposity
          uses: actions/checkout@v2
        - name: Create Medium Post
          uses: philips-software/post-to-medium-action@v0.4.1
          with:
            integration_token: "${{ secrets.MEDIUM_INTEGRATION_TOKEN }}"
            file: "${{ github.event.inputs.file }}"
            content_format: "markdown"
            notify_followers: "false"
            tags: "${{ github.event.inputs.tags }}"
            title: "${{ github.event.inputs.title }}"
            license: "all-rights-reserved"
            publish_status: "draft"
            parse_frontmatter: "true"